name: sandbox
on: 
  - workflow_dispatch
  - push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: echo "TRACER 28-OCT-2022 v2 hello from sandbox workflow"
